site_name: EGR 314 Matthew Sanderson Data Sheet
site_url: https://msande84.EGR314.github.io/
repo_url: https://github.com/msande84/msande84.EGR314.github.io/
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
  logo: static/logo314.svg
  favicon: static/logo314.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
#    - navigation.expand
#    - navigation.instant # doesn't work that well

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - 01 Requirements: 01-Requirements/Requirements.md
  - 02 Block Diagram: 02-Block-Diagram/Block-Diagram.md
  - 03 Component Selection: 03-Component-Selection/Component-Selection.md
  - 04 Microcontroller Selection: 04-Microcontroller-Selection/Microcontroller-Selection.md
  - 05 Power Budget: 05-Power-Budget/Power-Budget.md
  - 06 BOM: 06-BOM/BOM.md
  - 07 Schematic: 07-Schematic/Schematic.md
  - 08 PCB: 08-PCB/PCB.md
  - 09 API: 09-API/API.md
  - 10 Hardware V2.0: 10-Hardware V2.0/HardwareV2.md
  - 11 Resources: 11-Resources/Resources.md
  - 12 Reflection: 12-Reflection/Reflection.md
  - Appendix: Appendix/index.md
  
not_in_nav: |
  static
  
copyright: "Copyright &copy; 2026 Matthew Sanderson"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2026_spring
      name: 2026 Site    
